// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module vadd_center_vector_dispatcher (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        query_num_dout,
        query_num_num_data_valid,
        query_num_fifo_cap,
        query_num_empty_n,
        query_num_read,
        nprobe_dout,
        nprobe_num_data_valid,
        nprobe_fifo_cap,
        nprobe_empty_n,
        nprobe_read,
        s_center_vectors68_dout,
        s_center_vectors68_num_data_valid,
        s_center_vectors68_fifo_cap,
        s_center_vectors68_empty_n,
        s_center_vectors68_read,
        s_sub_center_vectors_i_0_din,
        s_sub_center_vectors_i_0_num_data_valid,
        s_sub_center_vectors_i_0_fifo_cap,
        s_sub_center_vectors_i_0_full_n,
        s_sub_center_vectors_i_0_write,
        s_sub_center_vectors_i_1_din,
        s_sub_center_vectors_i_1_num_data_valid,
        s_sub_center_vectors_i_1_fifo_cap,
        s_sub_center_vectors_i_1_full_n,
        s_sub_center_vectors_i_1_write,
        s_sub_center_vectors_i_2_din,
        s_sub_center_vectors_i_2_num_data_valid,
        s_sub_center_vectors_i_2_fifo_cap,
        s_sub_center_vectors_i_2_full_n,
        s_sub_center_vectors_i_2_write,
        s_sub_center_vectors_i_3_din,
        s_sub_center_vectors_i_3_num_data_valid,
        s_sub_center_vectors_i_3_fifo_cap,
        s_sub_center_vectors_i_3_full_n,
        s_sub_center_vectors_i_3_write,
        s_sub_center_vectors_i_4_din,
        s_sub_center_vectors_i_4_num_data_valid,
        s_sub_center_vectors_i_4_fifo_cap,
        s_sub_center_vectors_i_4_full_n,
        s_sub_center_vectors_i_4_write,
        s_sub_center_vectors_i_5_din,
        s_sub_center_vectors_i_5_num_data_valid,
        s_sub_center_vectors_i_5_fifo_cap,
        s_sub_center_vectors_i_5_full_n,
        s_sub_center_vectors_i_5_write,
        s_sub_center_vectors_i_6_din,
        s_sub_center_vectors_i_6_num_data_valid,
        s_sub_center_vectors_i_6_fifo_cap,
        s_sub_center_vectors_i_6_full_n,
        s_sub_center_vectors_i_6_write,
        s_sub_center_vectors_i_7_din,
        s_sub_center_vectors_i_7_num_data_valid,
        s_sub_center_vectors_i_7_fifo_cap,
        s_sub_center_vectors_i_7_full_n,
        s_sub_center_vectors_i_7_write,
        s_sub_center_vectors_i_8_din,
        s_sub_center_vectors_i_8_num_data_valid,
        s_sub_center_vectors_i_8_fifo_cap,
        s_sub_center_vectors_i_8_full_n,
        s_sub_center_vectors_i_8_write,
        s_sub_center_vectors_i_9_din,
        s_sub_center_vectors_i_9_num_data_valid,
        s_sub_center_vectors_i_9_fifo_cap,
        s_sub_center_vectors_i_9_full_n,
        s_sub_center_vectors_i_9_write,
        s_sub_center_vectors_i_10_din,
        s_sub_center_vectors_i_10_num_data_valid,
        s_sub_center_vectors_i_10_fifo_cap,
        s_sub_center_vectors_i_10_full_n,
        s_sub_center_vectors_i_10_write,
        s_sub_center_vectors_i_11_din,
        s_sub_center_vectors_i_11_num_data_valid,
        s_sub_center_vectors_i_11_fifo_cap,
        s_sub_center_vectors_i_11_full_n,
        s_sub_center_vectors_i_11_write,
        s_sub_center_vectors_i_12_din,
        s_sub_center_vectors_i_12_num_data_valid,
        s_sub_center_vectors_i_12_fifo_cap,
        s_sub_center_vectors_i_12_full_n,
        s_sub_center_vectors_i_12_write,
        s_sub_center_vectors_i_13_din,
        s_sub_center_vectors_i_13_num_data_valid,
        s_sub_center_vectors_i_13_fifo_cap,
        s_sub_center_vectors_i_13_full_n,
        s_sub_center_vectors_i_13_write,
        s_sub_center_vectors_i_14_din,
        s_sub_center_vectors_i_14_num_data_valid,
        s_sub_center_vectors_i_14_fifo_cap,
        s_sub_center_vectors_i_14_full_n,
        s_sub_center_vectors_i_14_write,
        s_sub_center_vectors_i_15_din,
        s_sub_center_vectors_i_15_num_data_valid,
        s_sub_center_vectors_i_15_fifo_cap,
        s_sub_center_vectors_i_15_full_n,
        s_sub_center_vectors_i_15_write,
        nprobe_c169_din,
        nprobe_c169_num_data_valid,
        nprobe_c169_fifo_cap,
        nprobe_c169_full_n,
        nprobe_c169_write,
        nprobe_c170_din,
        nprobe_c170_num_data_valid,
        nprobe_c170_fifo_cap,
        nprobe_c170_full_n,
        nprobe_c170_write,
        nprobe_c171_din,
        nprobe_c171_num_data_valid,
        nprobe_c171_fifo_cap,
        nprobe_c171_full_n,
        nprobe_c171_write,
        nprobe_c172_din,
        nprobe_c172_num_data_valid,
        nprobe_c172_fifo_cap,
        nprobe_c172_full_n,
        nprobe_c172_write,
        nprobe_c173_din,
        nprobe_c173_num_data_valid,
        nprobe_c173_fifo_cap,
        nprobe_c173_full_n,
        nprobe_c173_write,
        nprobe_c174_din,
        nprobe_c174_num_data_valid,
        nprobe_c174_fifo_cap,
        nprobe_c174_full_n,
        nprobe_c174_write,
        nprobe_c175_din,
        nprobe_c175_num_data_valid,
        nprobe_c175_fifo_cap,
        nprobe_c175_full_n,
        nprobe_c175_write,
        nprobe_c176_din,
        nprobe_c176_num_data_valid,
        nprobe_c176_fifo_cap,
        nprobe_c176_full_n,
        nprobe_c176_write,
        nprobe_c177_din,
        nprobe_c177_num_data_valid,
        nprobe_c177_fifo_cap,
        nprobe_c177_full_n,
        nprobe_c177_write,
        nprobe_c178_din,
        nprobe_c178_num_data_valid,
        nprobe_c178_fifo_cap,
        nprobe_c178_full_n,
        nprobe_c178_write,
        nprobe_c179_din,
        nprobe_c179_num_data_valid,
        nprobe_c179_fifo_cap,
        nprobe_c179_full_n,
        nprobe_c179_write,
        nprobe_c180_din,
        nprobe_c180_num_data_valid,
        nprobe_c180_fifo_cap,
        nprobe_c180_full_n,
        nprobe_c180_write,
        nprobe_c181_din,
        nprobe_c181_num_data_valid,
        nprobe_c181_fifo_cap,
        nprobe_c181_full_n,
        nprobe_c181_write,
        nprobe_c182_din,
        nprobe_c182_num_data_valid,
        nprobe_c182_fifo_cap,
        nprobe_c182_full_n,
        nprobe_c182_write,
        nprobe_c183_din,
        nprobe_c183_num_data_valid,
        nprobe_c183_fifo_cap,
        nprobe_c183_full_n,
        nprobe_c183_write,
        nprobe_c184_din,
        nprobe_c184_num_data_valid,
        nprobe_c184_fifo_cap,
        nprobe_c184_full_n,
        nprobe_c184_write,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] query_num_dout;
input  [1:0] query_num_num_data_valid;
input  [1:0] query_num_fifo_cap;
input   query_num_empty_n;
output   query_num_read;
input  [31:0] nprobe_dout;
input  [1:0] nprobe_num_data_valid;
input  [1:0] nprobe_fifo_cap;
input   nprobe_empty_n;
output   nprobe_read;
input  [511:0] s_center_vectors68_dout;
input  [8:0] s_center_vectors68_num_data_valid;
input  [8:0] s_center_vectors68_fifo_cap;
input   s_center_vectors68_empty_n;
output   s_center_vectors68_read;
output  [31:0] s_sub_center_vectors_i_0_din;
input  [1:0] s_sub_center_vectors_i_0_num_data_valid;
input  [1:0] s_sub_center_vectors_i_0_fifo_cap;
input   s_sub_center_vectors_i_0_full_n;
output   s_sub_center_vectors_i_0_write;
output  [31:0] s_sub_center_vectors_i_1_din;
input  [1:0] s_sub_center_vectors_i_1_num_data_valid;
input  [1:0] s_sub_center_vectors_i_1_fifo_cap;
input   s_sub_center_vectors_i_1_full_n;
output   s_sub_center_vectors_i_1_write;
output  [31:0] s_sub_center_vectors_i_2_din;
input  [1:0] s_sub_center_vectors_i_2_num_data_valid;
input  [1:0] s_sub_center_vectors_i_2_fifo_cap;
input   s_sub_center_vectors_i_2_full_n;
output   s_sub_center_vectors_i_2_write;
output  [31:0] s_sub_center_vectors_i_3_din;
input  [1:0] s_sub_center_vectors_i_3_num_data_valid;
input  [1:0] s_sub_center_vectors_i_3_fifo_cap;
input   s_sub_center_vectors_i_3_full_n;
output   s_sub_center_vectors_i_3_write;
output  [31:0] s_sub_center_vectors_i_4_din;
input  [1:0] s_sub_center_vectors_i_4_num_data_valid;
input  [1:0] s_sub_center_vectors_i_4_fifo_cap;
input   s_sub_center_vectors_i_4_full_n;
output   s_sub_center_vectors_i_4_write;
output  [31:0] s_sub_center_vectors_i_5_din;
input  [1:0] s_sub_center_vectors_i_5_num_data_valid;
input  [1:0] s_sub_center_vectors_i_5_fifo_cap;
input   s_sub_center_vectors_i_5_full_n;
output   s_sub_center_vectors_i_5_write;
output  [31:0] s_sub_center_vectors_i_6_din;
input  [1:0] s_sub_center_vectors_i_6_num_data_valid;
input  [1:0] s_sub_center_vectors_i_6_fifo_cap;
input   s_sub_center_vectors_i_6_full_n;
output   s_sub_center_vectors_i_6_write;
output  [31:0] s_sub_center_vectors_i_7_din;
input  [1:0] s_sub_center_vectors_i_7_num_data_valid;
input  [1:0] s_sub_center_vectors_i_7_fifo_cap;
input   s_sub_center_vectors_i_7_full_n;
output   s_sub_center_vectors_i_7_write;
output  [31:0] s_sub_center_vectors_i_8_din;
input  [1:0] s_sub_center_vectors_i_8_num_data_valid;
input  [1:0] s_sub_center_vectors_i_8_fifo_cap;
input   s_sub_center_vectors_i_8_full_n;
output   s_sub_center_vectors_i_8_write;
output  [31:0] s_sub_center_vectors_i_9_din;
input  [1:0] s_sub_center_vectors_i_9_num_data_valid;
input  [1:0] s_sub_center_vectors_i_9_fifo_cap;
input   s_sub_center_vectors_i_9_full_n;
output   s_sub_center_vectors_i_9_write;
output  [31:0] s_sub_center_vectors_i_10_din;
input  [1:0] s_sub_center_vectors_i_10_num_data_valid;
input  [1:0] s_sub_center_vectors_i_10_fifo_cap;
input   s_sub_center_vectors_i_10_full_n;
output   s_sub_center_vectors_i_10_write;
output  [31:0] s_sub_center_vectors_i_11_din;
input  [1:0] s_sub_center_vectors_i_11_num_data_valid;
input  [1:0] s_sub_center_vectors_i_11_fifo_cap;
input   s_sub_center_vectors_i_11_full_n;
output   s_sub_center_vectors_i_11_write;
output  [31:0] s_sub_center_vectors_i_12_din;
input  [1:0] s_sub_center_vectors_i_12_num_data_valid;
input  [1:0] s_sub_center_vectors_i_12_fifo_cap;
input   s_sub_center_vectors_i_12_full_n;
output   s_sub_center_vectors_i_12_write;
output  [31:0] s_sub_center_vectors_i_13_din;
input  [1:0] s_sub_center_vectors_i_13_num_data_valid;
input  [1:0] s_sub_center_vectors_i_13_fifo_cap;
input   s_sub_center_vectors_i_13_full_n;
output   s_sub_center_vectors_i_13_write;
output  [31:0] s_sub_center_vectors_i_14_din;
input  [1:0] s_sub_center_vectors_i_14_num_data_valid;
input  [1:0] s_sub_center_vectors_i_14_fifo_cap;
input   s_sub_center_vectors_i_14_full_n;
output   s_sub_center_vectors_i_14_write;
output  [31:0] s_sub_center_vectors_i_15_din;
input  [1:0] s_sub_center_vectors_i_15_num_data_valid;
input  [1:0] s_sub_center_vectors_i_15_fifo_cap;
input   s_sub_center_vectors_i_15_full_n;
output   s_sub_center_vectors_i_15_write;
output  [31:0] nprobe_c169_din;
input  [1:0] nprobe_c169_num_data_valid;
input  [1:0] nprobe_c169_fifo_cap;
input   nprobe_c169_full_n;
output   nprobe_c169_write;
output  [31:0] nprobe_c170_din;
input  [1:0] nprobe_c170_num_data_valid;
input  [1:0] nprobe_c170_fifo_cap;
input   nprobe_c170_full_n;
output   nprobe_c170_write;
output  [31:0] nprobe_c171_din;
input  [1:0] nprobe_c171_num_data_valid;
input  [1:0] nprobe_c171_fifo_cap;
input   nprobe_c171_full_n;
output   nprobe_c171_write;
output  [31:0] nprobe_c172_din;
input  [1:0] nprobe_c172_num_data_valid;
input  [1:0] nprobe_c172_fifo_cap;
input   nprobe_c172_full_n;
output   nprobe_c172_write;
output  [31:0] nprobe_c173_din;
input  [1:0] nprobe_c173_num_data_valid;
input  [1:0] nprobe_c173_fifo_cap;
input   nprobe_c173_full_n;
output   nprobe_c173_write;
output  [31:0] nprobe_c174_din;
input  [1:0] nprobe_c174_num_data_valid;
input  [1:0] nprobe_c174_fifo_cap;
input   nprobe_c174_full_n;
output   nprobe_c174_write;
output  [31:0] nprobe_c175_din;
input  [1:0] nprobe_c175_num_data_valid;
input  [1:0] nprobe_c175_fifo_cap;
input   nprobe_c175_full_n;
output   nprobe_c175_write;
output  [31:0] nprobe_c176_din;
input  [1:0] nprobe_c176_num_data_valid;
input  [1:0] nprobe_c176_fifo_cap;
input   nprobe_c176_full_n;
output   nprobe_c176_write;
output  [31:0] nprobe_c177_din;
input  [1:0] nprobe_c177_num_data_valid;
input  [1:0] nprobe_c177_fifo_cap;
input   nprobe_c177_full_n;
output   nprobe_c177_write;
output  [31:0] nprobe_c178_din;
input  [1:0] nprobe_c178_num_data_valid;
input  [1:0] nprobe_c178_fifo_cap;
input   nprobe_c178_full_n;
output   nprobe_c178_write;
output  [31:0] nprobe_c179_din;
input  [1:0] nprobe_c179_num_data_valid;
input  [1:0] nprobe_c179_fifo_cap;
input   nprobe_c179_full_n;
output   nprobe_c179_write;
output  [31:0] nprobe_c180_din;
input  [1:0] nprobe_c180_num_data_valid;
input  [1:0] nprobe_c180_fifo_cap;
input   nprobe_c180_full_n;
output   nprobe_c180_write;
output  [31:0] nprobe_c181_din;
input  [1:0] nprobe_c181_num_data_valid;
input  [1:0] nprobe_c181_fifo_cap;
input   nprobe_c181_full_n;
output   nprobe_c181_write;
output  [31:0] nprobe_c182_din;
input  [1:0] nprobe_c182_num_data_valid;
input  [1:0] nprobe_c182_fifo_cap;
input   nprobe_c182_full_n;
output   nprobe_c182_write;
output  [31:0] nprobe_c183_din;
input  [1:0] nprobe_c183_num_data_valid;
input  [1:0] nprobe_c183_fifo_cap;
input   nprobe_c183_full_n;
output   nprobe_c183_write;
output  [31:0] nprobe_c184_din;
input  [1:0] nprobe_c184_num_data_valid;
input  [1:0] nprobe_c184_fifo_cap;
input   nprobe_c184_full_n;
output   nprobe_c184_write;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg query_num_read;
reg nprobe_read;
reg s_center_vectors68_read;
reg s_sub_center_vectors_i_0_write;
reg s_sub_center_vectors_i_1_write;
reg s_sub_center_vectors_i_2_write;
reg s_sub_center_vectors_i_3_write;
reg s_sub_center_vectors_i_4_write;
reg s_sub_center_vectors_i_5_write;
reg s_sub_center_vectors_i_6_write;
reg s_sub_center_vectors_i_7_write;
reg s_sub_center_vectors_i_8_write;
reg s_sub_center_vectors_i_9_write;
reg s_sub_center_vectors_i_10_write;
reg s_sub_center_vectors_i_11_write;
reg s_sub_center_vectors_i_12_write;
reg s_sub_center_vectors_i_13_write;
reg s_sub_center_vectors_i_14_write;
reg s_sub_center_vectors_i_15_write;
reg nprobe_c169_write;
reg nprobe_c170_write;
reg nprobe_c171_write;
reg nprobe_c172_write;
reg nprobe_c173_write;
reg nprobe_c174_write;
reg nprobe_c175_write;
reg nprobe_c176_write;
reg nprobe_c177_write;
reg nprobe_c178_write;
reg nprobe_c179_write;
reg nprobe_c180_write;
reg nprobe_c181_write;
reg nprobe_c182_write;
reg nprobe_c183_write;
reg nprobe_c184_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    query_num_blk_n;
reg    nprobe_blk_n;
reg    s_center_vectors68_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln123_fu_373_p2;
reg    nprobe_c169_blk_n;
reg    nprobe_c170_blk_n;
reg    nprobe_c171_blk_n;
reg    nprobe_c172_blk_n;
reg    nprobe_c173_blk_n;
reg    nprobe_c174_blk_n;
reg    nprobe_c175_blk_n;
reg    nprobe_c176_blk_n;
reg    nprobe_c177_blk_n;
reg    nprobe_c178_blk_n;
reg    nprobe_c179_blk_n;
reg    nprobe_c180_blk_n;
reg    nprobe_c181_blk_n;
reg    nprobe_c182_blk_n;
reg    nprobe_c183_blk_n;
reg    nprobe_c184_blk_n;
wire   [63:0] bound4_fu_348_p2;
reg   [63:0] bound4_reg_405;
wire   [63:0] add_ln118_fu_367_p2;
reg   [63:0] add_ln118_reg_413;
wire    ap_CS_fsm_state2;
wire   [4:0] add_ln123_fu_379_p2;
reg   [4:0] add_ln123_reg_421;
reg    ap_block_state3;
reg   [511:0] reg_V_reg_426;
wire   [8:0] tmp_fu_385_p3;
reg   [8:0] tmp_reg_431;
reg   [8:0] center_vector_buffer_address0;
reg    center_vector_buffer_ce0;
reg    center_vector_buffer_we0;
wire   [31:0] center_vector_buffer_q0;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_start;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_done;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_idle;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_ready;
wire   [8:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_center_vector_buffer_address0;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_center_vector_buffer_ce0;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_center_vector_buffer_we0;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_center_vector_buffer_d0;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_ext_blocking_n;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_str_blocking_n;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_int_blocking_n;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_start;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_done;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_idle;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_ready;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_14_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_14_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_13_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_13_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_12_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_12_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_11_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_11_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_10_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_10_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_9_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_9_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_8_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_8_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_7_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_7_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_6_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_6_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_5_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_5_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_4_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_4_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_3_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_3_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_2_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_2_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_1_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_1_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_0_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_0_write;
wire   [31:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_15_din;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_15_write;
wire   [8:0] grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_center_vector_buffer_address0;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_center_vector_buffer_ce0;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_ext_blocking_n;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_str_blocking_n;
wire    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_int_blocking_n;
reg   [4:0] i_reg_284;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln118_fu_362_p2;
reg    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_start_reg;
reg    ap_block_state3_ignore_call3;
reg    grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_start_reg;
reg    ap_block_state3_ignore_call1;
wire    ap_CS_fsm_state5;
reg   [63:0] indvar_flatten6_fu_130;
reg    ap_block_state1;
wire   [31:0] bound4_fu_348_p0;
wire   [31:0] bound4_fu_348_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_int_blocking_cur_n;
reg    ap_ext_blocking_sub_n;
reg    ap_wait_0;
reg    ap_sub_ext_blocking_0;
reg    ap_wait_1;
reg    ap_sub_ext_blocking_1;
reg    ap_str_blocking_sub_n;
reg    ap_sub_str_blocking_0;
reg    ap_sub_str_blocking_1;
reg    ap_int_blocking_sub_n;
reg    ap_sub_int_blocking_0;
reg    ap_sub_int_blocking_1;
wire   [63:0] bound4_fu_348_p00;
wire   [63:0] bound4_fu_348_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_start_reg = 1'b0;
#0 grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_start_reg = 1'b0;
end

vadd_center_vector_dispatcher_center_vector_buffer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 384 ),
    .AddressWidth( 9 ))
center_vector_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(center_vector_buffer_address0),
    .ce0(center_vector_buffer_ce0),
    .we0(center_vector_buffer_we0),
    .d0(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_center_vector_buffer_d0),
    .q0(center_vector_buffer_q0)
);

vadd_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4 grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_start),
    .ap_done(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_done),
    .ap_idle(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_idle),
    .ap_ready(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_ready),
    .reg_V(reg_V_reg_426),
    .tmp(tmp_reg_431),
    .center_vector_buffer_address0(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_center_vector_buffer_address0),
    .center_vector_buffer_ce0(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_center_vector_buffer_ce0),
    .center_vector_buffer_we0(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_center_vector_buffer_we0),
    .center_vector_buffer_d0(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_center_vector_buffer_d0),
    .ap_ext_blocking_n(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_str_blocking_n),
    .ap_int_blocking_n(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_int_blocking_n)
);

vadd_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6 grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_start),
    .ap_done(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_done),
    .ap_idle(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_idle),
    .ap_ready(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_ready),
    .s_sub_center_vectors_i_14_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_14_din),
    .s_sub_center_vectors_i_14_num_data_valid(2'd0),
    .s_sub_center_vectors_i_14_fifo_cap(2'd0),
    .s_sub_center_vectors_i_14_full_n(s_sub_center_vectors_i_14_full_n),
    .s_sub_center_vectors_i_14_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_14_write),
    .s_sub_center_vectors_i_13_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_13_din),
    .s_sub_center_vectors_i_13_num_data_valid(2'd0),
    .s_sub_center_vectors_i_13_fifo_cap(2'd0),
    .s_sub_center_vectors_i_13_full_n(s_sub_center_vectors_i_13_full_n),
    .s_sub_center_vectors_i_13_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_13_write),
    .s_sub_center_vectors_i_12_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_12_din),
    .s_sub_center_vectors_i_12_num_data_valid(2'd0),
    .s_sub_center_vectors_i_12_fifo_cap(2'd0),
    .s_sub_center_vectors_i_12_full_n(s_sub_center_vectors_i_12_full_n),
    .s_sub_center_vectors_i_12_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_12_write),
    .s_sub_center_vectors_i_11_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_11_din),
    .s_sub_center_vectors_i_11_num_data_valid(2'd0),
    .s_sub_center_vectors_i_11_fifo_cap(2'd0),
    .s_sub_center_vectors_i_11_full_n(s_sub_center_vectors_i_11_full_n),
    .s_sub_center_vectors_i_11_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_11_write),
    .s_sub_center_vectors_i_10_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_10_din),
    .s_sub_center_vectors_i_10_num_data_valid(2'd0),
    .s_sub_center_vectors_i_10_fifo_cap(2'd0),
    .s_sub_center_vectors_i_10_full_n(s_sub_center_vectors_i_10_full_n),
    .s_sub_center_vectors_i_10_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_10_write),
    .s_sub_center_vectors_i_9_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_9_din),
    .s_sub_center_vectors_i_9_num_data_valid(2'd0),
    .s_sub_center_vectors_i_9_fifo_cap(2'd0),
    .s_sub_center_vectors_i_9_full_n(s_sub_center_vectors_i_9_full_n),
    .s_sub_center_vectors_i_9_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_9_write),
    .s_sub_center_vectors_i_8_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_8_din),
    .s_sub_center_vectors_i_8_num_data_valid(2'd0),
    .s_sub_center_vectors_i_8_fifo_cap(2'd0),
    .s_sub_center_vectors_i_8_full_n(s_sub_center_vectors_i_8_full_n),
    .s_sub_center_vectors_i_8_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_8_write),
    .s_sub_center_vectors_i_7_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_7_din),
    .s_sub_center_vectors_i_7_num_data_valid(2'd0),
    .s_sub_center_vectors_i_7_fifo_cap(2'd0),
    .s_sub_center_vectors_i_7_full_n(s_sub_center_vectors_i_7_full_n),
    .s_sub_center_vectors_i_7_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_7_write),
    .s_sub_center_vectors_i_6_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_6_din),
    .s_sub_center_vectors_i_6_num_data_valid(2'd0),
    .s_sub_center_vectors_i_6_fifo_cap(2'd0),
    .s_sub_center_vectors_i_6_full_n(s_sub_center_vectors_i_6_full_n),
    .s_sub_center_vectors_i_6_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_6_write),
    .s_sub_center_vectors_i_5_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_5_din),
    .s_sub_center_vectors_i_5_num_data_valid(2'd0),
    .s_sub_center_vectors_i_5_fifo_cap(2'd0),
    .s_sub_center_vectors_i_5_full_n(s_sub_center_vectors_i_5_full_n),
    .s_sub_center_vectors_i_5_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_5_write),
    .s_sub_center_vectors_i_4_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_4_din),
    .s_sub_center_vectors_i_4_num_data_valid(2'd0),
    .s_sub_center_vectors_i_4_fifo_cap(2'd0),
    .s_sub_center_vectors_i_4_full_n(s_sub_center_vectors_i_4_full_n),
    .s_sub_center_vectors_i_4_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_4_write),
    .s_sub_center_vectors_i_3_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_3_din),
    .s_sub_center_vectors_i_3_num_data_valid(2'd0),
    .s_sub_center_vectors_i_3_fifo_cap(2'd0),
    .s_sub_center_vectors_i_3_full_n(s_sub_center_vectors_i_3_full_n),
    .s_sub_center_vectors_i_3_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_3_write),
    .s_sub_center_vectors_i_2_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_2_din),
    .s_sub_center_vectors_i_2_num_data_valid(2'd0),
    .s_sub_center_vectors_i_2_fifo_cap(2'd0),
    .s_sub_center_vectors_i_2_full_n(s_sub_center_vectors_i_2_full_n),
    .s_sub_center_vectors_i_2_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_2_write),
    .s_sub_center_vectors_i_1_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_1_din),
    .s_sub_center_vectors_i_1_num_data_valid(2'd0),
    .s_sub_center_vectors_i_1_fifo_cap(2'd0),
    .s_sub_center_vectors_i_1_full_n(s_sub_center_vectors_i_1_full_n),
    .s_sub_center_vectors_i_1_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_1_write),
    .s_sub_center_vectors_i_0_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_0_din),
    .s_sub_center_vectors_i_0_num_data_valid(2'd0),
    .s_sub_center_vectors_i_0_fifo_cap(2'd0),
    .s_sub_center_vectors_i_0_full_n(s_sub_center_vectors_i_0_full_n),
    .s_sub_center_vectors_i_0_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_0_write),
    .s_sub_center_vectors_i_15_din(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_15_din),
    .s_sub_center_vectors_i_15_num_data_valid(2'd0),
    .s_sub_center_vectors_i_15_fifo_cap(2'd0),
    .s_sub_center_vectors_i_15_full_n(s_sub_center_vectors_i_15_full_n),
    .s_sub_center_vectors_i_15_write(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_15_write),
    .center_vector_buffer_address0(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_center_vector_buffer_address0),
    .center_vector_buffer_ce0(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_center_vector_buffer_ce0),
    .center_vector_buffer_q0(center_vector_buffer_q0),
    .ap_ext_blocking_n(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_str_blocking_n),
    .ap_int_blocking_n(grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_int_blocking_n)
);

vadd_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U147(
    .din0(bound4_fu_348_p0),
    .din1(bound4_fu_348_p1),
    .dout(bound4_fu_348_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln118_fu_362_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_start_reg <= 1'b0;
    end else begin
        if ((~((s_center_vectors68_empty_n == 1'b0) & (icmp_ln123_fu_373_p2 == 1'd0)) & (icmp_ln123_fu_373_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_start_reg <= 1'b1;
        end else if ((grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_ready == 1'b1)) begin
            grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_start_reg <= 1'b0;
    end else begin
        if ((~((s_center_vectors68_empty_n == 1'b0) & (icmp_ln123_fu_373_p2 == 1'd0)) & (icmp_ln123_fu_373_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_start_reg <= 1'b1;
        end else if ((grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_ready == 1'b1)) begin
            grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_fu_362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_284 <= 5'd0;
    end else if (((grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        i_reg_284 <= add_ln123_reg_421;
    end
end

always @ (posedge ap_clk) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten6_fu_130 <= 64'd0;
    end else if ((~((s_center_vectors68_empty_n == 1'b0) & (icmp_ln123_fu_373_p2 == 1'd0)) & (icmp_ln123_fu_373_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        indvar_flatten6_fu_130 <= add_ln118_reg_413;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln118_reg_413 <= add_ln118_fu_367_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((s_center_vectors68_empty_n == 1'b0) & (icmp_ln123_fu_373_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3))) begin
        add_ln123_reg_421 <= add_ln123_fu_379_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bound4_reg_405 <= bound4_fu_348_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln123_fu_373_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_V_reg_426 <= s_center_vectors68_dout;
        tmp_reg_431[8 : 4] <= tmp_fu_385_p3[8 : 4];
    end
end

always @ (*) begin
    if (((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((s_center_vectors68_empty_n == 1'b0) & (icmp_ln123_fu_373_p2 == 1'd0))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln118_fu_362_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if ((((ap_wait_1 & ap_sub_ext_blocking_1) == 1'b1) & ((ap_wait_0 & ap_sub_ext_blocking_0) == 1'b1))) begin
        ap_ext_blocking_sub_n = 1'b0;
    end else begin
        ap_ext_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_wait_1 & ap_sub_int_blocking_1) == 1'b1) & ((ap_wait_0 & ap_sub_int_blocking_0) == 1'b1))) begin
        ap_int_blocking_sub_n = 1'b0;
    end else begin
        ap_int_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln118_fu_362_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_wait_1 & ap_sub_str_blocking_1) == 1'b1) & ((ap_wait_0 & ap_sub_str_blocking_0) == 1'b1))) begin
        ap_str_blocking_sub_n = 1'b0;
    end else begin
        ap_str_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if ((grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_0 = 1'b1;
    end else begin
        ap_sub_ext_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_1 = 1'b1;
    end else begin
        ap_sub_ext_blocking_1 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_0 = 1'b1;
    end else begin
        ap_sub_int_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_1 = 1'b1;
    end else begin
        ap_sub_int_blocking_1 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_0 = 1'b1;
    end else begin
        ap_sub_str_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_1 = 1'b1;
    end else begin
        ap_sub_str_blocking_1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state4 == ap_CS_fsm)) begin
        ap_wait_0 = 1'b1;
    end else begin
        ap_wait_0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state5 == ap_CS_fsm)) begin
        ap_wait_1 = 1'b1;
    end else begin
        ap_wait_1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        center_vector_buffer_address0 = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_center_vector_buffer_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        center_vector_buffer_address0 = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_center_vector_buffer_address0;
    end else begin
        center_vector_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        center_vector_buffer_ce0 = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_center_vector_buffer_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        center_vector_buffer_ce0 = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_center_vector_buffer_ce0;
    end else begin
        center_vector_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        center_vector_buffer_we0 = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_center_vector_buffer_we0;
    end else begin
        center_vector_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_blk_n = nprobe_empty_n;
    end else begin
        nprobe_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c169_blk_n = nprobe_c169_full_n;
    end else begin
        nprobe_c169_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c169_write = 1'b1;
    end else begin
        nprobe_c169_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c170_blk_n = nprobe_c170_full_n;
    end else begin
        nprobe_c170_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c170_write = 1'b1;
    end else begin
        nprobe_c170_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c171_blk_n = nprobe_c171_full_n;
    end else begin
        nprobe_c171_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c171_write = 1'b1;
    end else begin
        nprobe_c171_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c172_blk_n = nprobe_c172_full_n;
    end else begin
        nprobe_c172_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c172_write = 1'b1;
    end else begin
        nprobe_c172_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c173_blk_n = nprobe_c173_full_n;
    end else begin
        nprobe_c173_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c173_write = 1'b1;
    end else begin
        nprobe_c173_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c174_blk_n = nprobe_c174_full_n;
    end else begin
        nprobe_c174_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c174_write = 1'b1;
    end else begin
        nprobe_c174_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c175_blk_n = nprobe_c175_full_n;
    end else begin
        nprobe_c175_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c175_write = 1'b1;
    end else begin
        nprobe_c175_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c176_blk_n = nprobe_c176_full_n;
    end else begin
        nprobe_c176_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c176_write = 1'b1;
    end else begin
        nprobe_c176_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c177_blk_n = nprobe_c177_full_n;
    end else begin
        nprobe_c177_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c177_write = 1'b1;
    end else begin
        nprobe_c177_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c178_blk_n = nprobe_c178_full_n;
    end else begin
        nprobe_c178_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c178_write = 1'b1;
    end else begin
        nprobe_c178_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c179_blk_n = nprobe_c179_full_n;
    end else begin
        nprobe_c179_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c179_write = 1'b1;
    end else begin
        nprobe_c179_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c180_blk_n = nprobe_c180_full_n;
    end else begin
        nprobe_c180_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c180_write = 1'b1;
    end else begin
        nprobe_c180_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c181_blk_n = nprobe_c181_full_n;
    end else begin
        nprobe_c181_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c181_write = 1'b1;
    end else begin
        nprobe_c181_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c182_blk_n = nprobe_c182_full_n;
    end else begin
        nprobe_c182_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c182_write = 1'b1;
    end else begin
        nprobe_c182_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c183_blk_n = nprobe_c183_full_n;
    end else begin
        nprobe_c183_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c183_write = 1'b1;
    end else begin
        nprobe_c183_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c184_blk_n = nprobe_c184_full_n;
    end else begin
        nprobe_c184_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_c184_write = 1'b1;
    end else begin
        nprobe_c184_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nprobe_read = 1'b1;
    end else begin
        nprobe_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        query_num_blk_n = query_num_empty_n;
    end else begin
        query_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        query_num_read = 1'b1;
    end else begin
        query_num_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln123_fu_373_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        s_center_vectors68_blk_n = s_center_vectors68_empty_n;
    end else begin
        s_center_vectors68_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((s_center_vectors68_empty_n == 1'b0) & (icmp_ln123_fu_373_p2 == 1'd0)) & (icmp_ln123_fu_373_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        s_center_vectors68_read = 1'b1;
    end else begin
        s_center_vectors68_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_0_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_0_write;
    end else begin
        s_sub_center_vectors_i_0_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_10_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_10_write;
    end else begin
        s_sub_center_vectors_i_10_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_11_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_11_write;
    end else begin
        s_sub_center_vectors_i_11_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_12_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_12_write;
    end else begin
        s_sub_center_vectors_i_12_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_13_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_13_write;
    end else begin
        s_sub_center_vectors_i_13_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_14_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_14_write;
    end else begin
        s_sub_center_vectors_i_14_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_15_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_15_write;
    end else begin
        s_sub_center_vectors_i_15_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_1_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_1_write;
    end else begin
        s_sub_center_vectors_i_1_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_2_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_2_write;
    end else begin
        s_sub_center_vectors_i_2_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_3_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_3_write;
    end else begin
        s_sub_center_vectors_i_3_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_4_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_4_write;
    end else begin
        s_sub_center_vectors_i_4_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_5_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_5_write;
    end else begin
        s_sub_center_vectors_i_5_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_6_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_6_write;
    end else begin
        s_sub_center_vectors_i_6_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_7_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_7_write;
    end else begin
        s_sub_center_vectors_i_7_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_8_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_8_write;
    end else begin
        s_sub_center_vectors_i_8_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_sub_center_vectors_i_9_write = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_9_write;
    end else begin
        s_sub_center_vectors_i_9_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln118_fu_362_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((s_center_vectors68_empty_n == 1'b0) & (icmp_ln123_fu_373_p2 == 1'd0)) & (icmp_ln123_fu_373_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if ((~((s_center_vectors68_empty_n == 1'b0) & (icmp_ln123_fu_373_p2 == 1'd0)) & (icmp_ln123_fu_373_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln118_fu_367_p2 = (indvar_flatten6_fu_130 + 64'd1);

assign add_ln123_fu_379_p2 = (i_reg_284 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((nprobe_empty_n == 1'b0) | (query_num_empty_n == 1'b0) | (nprobe_c184_full_n == 1'b0) | (nprobe_c183_full_n == 1'b0) | (nprobe_c182_full_n == 1'b0) | (nprobe_c181_full_n == 1'b0) | (nprobe_c180_full_n == 1'b0) | (nprobe_c179_full_n == 1'b0) | (nprobe_c178_full_n == 1'b0) | (nprobe_c177_full_n == 1'b0) | (nprobe_c176_full_n == 1'b0) | (nprobe_c175_full_n == 1'b0) | (nprobe_c174_full_n == 1'b0) | (nprobe_c173_full_n == 1'b0) | (nprobe_c172_full_n == 1'b0) | (nprobe_c171_full_n == 1'b0) | (nprobe_c170_full_n == 1'b0) | (ap_done_reg == 1'b1) | (nprobe_c169_full_n == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((s_center_vectors68_empty_n == 1'b0) & (icmp_ln123_fu_373_p2 == 1'd0));
end

always @ (*) begin
    ap_block_state3_ignore_call1 = ((s_center_vectors68_empty_n == 1'b0) & (icmp_ln123_fu_373_p2 == 1'd0));
end

always @ (*) begin
    ap_block_state3_ignore_call3 = ((s_center_vectors68_empty_n == 1'b0) & (icmp_ln123_fu_373_p2 == 1'd0));
end

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & 1'b1);

assign ap_int_blocking_cur_n = (s_center_vectors68_blk_n & query_num_blk_n & nprobe_c184_blk_n & nprobe_c183_blk_n & nprobe_c182_blk_n & nprobe_c181_blk_n & nprobe_c180_blk_n & nprobe_c179_blk_n & nprobe_c178_blk_n & nprobe_c177_blk_n & nprobe_c176_blk_n & nprobe_c175_blk_n & nprobe_c174_blk_n & nprobe_c173_blk_n & nprobe_c172_blk_n & nprobe_c171_blk_n & nprobe_c170_blk_n & nprobe_c169_blk_n & nprobe_blk_n);

assign ap_int_blocking_n = (ap_int_blocking_sub_n & ap_int_blocking_cur_n);

assign ap_str_blocking_n = (ap_str_blocking_sub_n & 1'b1);

assign bound4_fu_348_p0 = bound4_fu_348_p00;

assign bound4_fu_348_p00 = query_num_dout;

assign bound4_fu_348_p1 = bound4_fu_348_p10;

assign bound4_fu_348_p10 = nprobe_dout;

assign grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_start = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_127_4_fu_295_ap_start_reg;

assign grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_start = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_ap_start_reg;

assign icmp_ln118_fu_362_p2 = ((indvar_flatten6_fu_130 == bound4_reg_405) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_373_p2 = ((i_reg_284 == 5'd24) ? 1'b1 : 1'b0);

assign nprobe_c169_din = nprobe_dout;

assign nprobe_c170_din = nprobe_dout;

assign nprobe_c171_din = nprobe_dout;

assign nprobe_c172_din = nprobe_dout;

assign nprobe_c173_din = nprobe_dout;

assign nprobe_c174_din = nprobe_dout;

assign nprobe_c175_din = nprobe_dout;

assign nprobe_c176_din = nprobe_dout;

assign nprobe_c177_din = nprobe_dout;

assign nprobe_c178_din = nprobe_dout;

assign nprobe_c179_din = nprobe_dout;

assign nprobe_c180_din = nprobe_dout;

assign nprobe_c181_din = nprobe_dout;

assign nprobe_c182_din = nprobe_dout;

assign nprobe_c183_din = nprobe_dout;

assign nprobe_c184_din = nprobe_dout;

assign s_sub_center_vectors_i_0_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_0_din;

assign s_sub_center_vectors_i_10_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_10_din;

assign s_sub_center_vectors_i_11_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_11_din;

assign s_sub_center_vectors_i_12_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_12_din;

assign s_sub_center_vectors_i_13_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_13_din;

assign s_sub_center_vectors_i_14_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_14_din;

assign s_sub_center_vectors_i_15_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_15_din;

assign s_sub_center_vectors_i_1_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_1_din;

assign s_sub_center_vectors_i_2_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_2_din;

assign s_sub_center_vectors_i_3_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_3_din;

assign s_sub_center_vectors_i_4_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_4_din;

assign s_sub_center_vectors_i_5_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_5_din;

assign s_sub_center_vectors_i_6_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_6_din;

assign s_sub_center_vectors_i_7_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_7_din;

assign s_sub_center_vectors_i_8_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_8_din;

assign s_sub_center_vectors_i_9_din = grp_center_vector_dispatcher_Pipeline_VITIS_LOOP_139_5_VITIS_LOOP_140_6_fu_303_s_sub_center_vectors_i_9_din;

assign tmp_fu_385_p3 = {{i_reg_284}, {4'd0}};

always @ (posedge ap_clk) begin
    tmp_reg_431[3:0] <= 4'b0000;
end

endmodule //vadd_center_vector_dispatcher
